version: "3"
services:

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madgex
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

