version: "3"
services:
  app:
    container_name: app
    build: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/madgex
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run start --prefix ./server
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madgex
    volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql